### ISSUE TITLE
Suggestions for data structure of google sheet

### ISSUE THREAD

**Issue by stefanwezel** [sportypenguins/jumpjumpwaddle#5]
Think of how the google sheet needs to be structured that we can work effectively with it.

**Comment by OldFella** [comment]
ideas:
1. one dataframe for all workouts, with columns:
   workout_name | set_no | exercise_name | exercise_duration | description

2. one dataframe for each individual workout, with columns:
    set_no | exercise_name | exercise_duration | description

3. something different?

**Comment by stefanwezel** [comment]
Continued in  #6
